<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $conn = $manager->getConnection();
        $rawSql = "INSERT INTO `type` (nom, montagne, prairie, ville, foret, plage) 
                            VALUES ('Acier', 1, 0, 0, 0, 0), 
                                   ('Combat', 0, 0, 1, 0, 0),
                                   ('Dragon', 1, 0, 0, 0, 1),
                                   ('Eau', 0, 0, 0, 0, 1),
                                   ('Electrik', 0, 0, 1, 0, 0),
                                   ('Feu', 0, 1, 0, 0, 0),
                                   ('Glace', 1, 0, 0, 0, 0),
                                   ('Insecte', 0, 0, 0, 1, 0),
                                   ('Normal', 1, 1, 1, 1, 1),
                                   ('Plante', 0, 1, 0, 0, 0),
                                   ('Poison', 0, 0, 0, 0, 1),
                                   ('Psy', 0, 0, 1, 0, 0),
                                   ('Roche', 1, 0, 0, 0, 0),
                                   ('Sol', 0, 1, 0, 0, 0),
                                   ('Spectre', 0, 0, 0, 1, 0),
                                   ('Vol', 0, 1, 0, 1, 0),
                                   ('Fee', 0, 1, 0, 0, 0);";
        $stmt = $conn->prepare($rawSql);
        $stmt->execute();

        $conn = $manager->getConnection();
        $rawSql = "INSERT INTO espece (nom, courbe_xp, evolution)
                            VALUES ('Bulbizarre', 'P', 'n'),
                                    ('Herbizarre', 'P', 'o'),
                                    ('Florizarre', 'P', 'o'),
                                    ('Salameche', 'P', 'n'),
                                    ('Reptincel', 'P', 'o'),
                                    ('Dracaufeu', 'P', 'o'),
                                    ('Carapuce', 'P', 'n'),
                                    ('Carabaffe', 'P', 'o'),
                                    ('Tortank', 'P', 'o'),
                                    ('Chenipan', 'M', 'n'),
                                    ('Chrysacier', 'M', 'o'),
                                    ('Papilusion', 'M', 'o'),
                                    ('Aspicot', 'M', 'n'),
                                    ('Coconfort', 'M', 'o'),
                                    ('Dardargnan', 'M', 'o'),
                                    ('Roucool', 'P', 'n'),
                                    ('Roucoups', 'P', 'o'),
                                    ('Roucarnage', 'P', 'o'),
                                    ('Rattata', 'M', 'n'),
                                    ('Rattatac', 'M', 'o'),
                                    ('Piafabec', 'M', 'n'),
                                    ('Rapasdepic', 'M', 'o'),
                                    ('Abo', 'M', 'n'),
                                    ('Arbok', 'M', 'o'),
                                    ('Pikachu', 'M', 'n'),
                                    ('Raichu', 'M', 'o'),
                                    ('Sabelette', 'M', 'n'),
                                    ('Sablaireau', 'M', 'o'),
                                    ('Nidoran', 'P', 'n'),
                                    ('Nidorina', 'P', 'o'),
                                    ('Nidoqueen', 'P', 'o'),
                                    ('Nidoran', 'P', 'n'),
                                    ('Nidorino', 'P', 'o'),
                                    ('Nidoking', 'P', 'o'),
                                    ('Mélofée', 'R', 'n'),
                                    ('Mélodelfe', 'R', 'o'),
                                    ('Goupix', 'M', 'n'),
                                    ('Feunard', 'M', 'o'),
                                    ('Rondoudou', 'R', 'n'),
                                    ('Grodoudou', 'R', 'o'),
                                    ('Nosferapti', 'M', 'n'),
                                    ('Nosferalto', 'M', 'o'),
                                    ('Mystherbe', 'P', 'n'),
                                    ('Ortide', 'P', 'o'),
                                    ('Rafflesia', 'P', 'o'),
                                    ('Paras', 'M', 'n'),
                                    ('Parasect', 'M', 'o'),
                                    ('Mimitoss', 'M', 'n'),
                                    ('Aéromite', 'M', 'o'),
                                    ('Taupiqueur', 'M', 'n'),
                                    ('Triopikeur', 'M', 'o'),
                                    ('Miaouss', 'M', 'n'),
                                    ('Persian', 'M', 'o'),
                                    ('Psykokwak', 'M', 'n'),
                                    ('Akwakwak', 'M', 'o'),
                                    ('Férosinge', 'M', 'n'),
                                    ('Colossinge', 'M', 'o'),
                                    ('Caninos', 'L', 'n'),
                                    ('Arcanin', 'L', 'o'),
                                    ('Ptitard', 'P', 'n'),
                                    ('Tétarte', 'P', 'o'),
                                    ('Tartard', 'P', 'o'),
                                    ('Abra', 'P', 'n'),
                                    ('Kadabra', 'P', 'o'),
                                    ('Alakazam', 'P', 'o'),
                                    ('Machoc', 'P', 'n'),
                                    ('Machopeur', 'P', 'o'),
                                    ('Mackogneur', 'P', 'o'),
                                    ('Chétiflor', 'P', 'n'),
                                    ('Boustiflor', 'P', 'o'),
                                    ('Empiflor', 'P', 'o'),
                                    ('Tentacool', 'L', 'n'),
                                    ('Tentacruel', 'L', 'o'),
                                    ('Racaillou', 'P', 'n'),
                                    ('Gravalanch', 'P', 'o'),
                                    ('Grolem', 'P', 'o'),
                                    ('Ponyta', 'M', 'n'),
                                    ('Galopa', 'M', 'o'),
                                    ('Ramoloss', 'M', 'n'),
                                    ('Flagadoss', 'M', 'o'),
                                    ('MagnÃ©ti', 'M', 'n'),
                                    ('MagnÃŒÂ©ton', 'M', 'o'),
                                    ('Canarticho', 'M', 'n'),
                                    ('Doduo', 'M', 'n'),
                                    ('Dodrio', 'M', 'o'),
                                    ('Otaria', 'M', 'n'),
                                    ('Lamantine', 'M', 'o'),
                                    ('Tadmorv', 'M', 'n'),
                                    ('Grotadmorv', 'M', 'o'),
                                    ('Kokiyas', 'L', 'n'),
                                    ('Crustabri', 'L', 'o'),
                                    ('Fantominus', 'P', 'n'),
                                    ('Spectrum', 'P', 'o'),
                                    ('Ectoplasma', 'P', 'o'),
                                    ('Onix', 'M', 'n'),
                                    ('Soporifik', 'M', 'n'),
                                    ('Hypnomade', 'M', 'o'),
                                    ('Krabby', 'M', 'n'),
                                    ('Krabboss', 'M', 'o'),
                                    ('Voltorbe', 'M', 'n'),
                                    ('Electrode', 'M', 'o'),
                                    ('Noeunoeuf', 'L', 'n'),
                                    ('Noadkoko', 'L', 'o'),
                                    ('Osselait', 'M', 'n'),
                                    ('Ossatueur', 'M', 'o'),
                                    ('Kicklee', 'M', 'n'),
                                    ('Tygnon', 'M', 'n'),
                                    ('Excelangue', 'M', 'n'),
                                    ('Smogo', 'M', 'n'),
                                    ('Smogogo', 'M', 'o'),
                                    ('Rhinocorne', 'L', 'n'),
                                    ('Rhinoféros', 'L', 'o'),
                                    ('Leveinard', 'R', 'n'),
                                    ('Saquedeneu', 'M', 'n'),
                                    ('Kangourex', 'M', 'n'),
                                    ('Hypotrempe', 'M', 'n'),
                                    ('Hypocéan', 'M', 'o'),
                                    ('Poissirène', 'M', 'n'),
                                    ('Poissoroy', 'M', 'o'),
                                    ('Stari', 'L', 'n'),
                                    ('Staross', 'L', 'o'),
                                    ('M. Mime', 'M', 'n'),
                                    ('Insécateur', 'M', 'n'),
                                    ('Lippoutou', 'M', 'n'),
                                    ('Elektek', 'M', 'n'),
                                    ('Magmar', 'M', 'n'),
                                    ('Scarabrute', 'L', 'n'),
                                    ('Tauros', 'L', 'n'),
                                    ('Magicarpe', 'L', 'n'),
                                    ('Léviator', 'L', 'o'),
                                    ('Lokhlass', 'L', 'n'),
                                    ('Métamorph', 'M', 'n'),
                                    ('Evoli', 'M', 'n'),
                                    ('Aquali', 'M', 'o'),
                                    ('Voltali', 'M', 'o'),
                                    ('Pyroli', 'M', 'o'),
                                    ('Porygon', 'M', 'n'),
                                    ('Amonita', 'M', 'n'),
                                    ('Amonistar', 'M', 'o'),
                                    ('Kabuto', 'M', 'n'),
                                    ('Kabutops', 'M', 'o'),
                                    ('Ptéra', 'L', 'n'),
                                    ('Ronflex', 'L', 'n'),
                                    ('Artikodin', 'L', 'n'),
                                    ('Electhor', 'L', 'n'),
                                    ('Sulfura', 'L', 'n'),
                                    ('Minidraco', 'L', 'n'),
                                    ('Draco', 'L', 'o'),
                                    ('Dracolosse', 'L', 'o'),
                                    ('Mewtwo', 'L', 'n'),
                                    ('Mew', 'P', 'n');";
        $stmt = $conn->prepare($rawSql);
        $stmt->execute();

        $conn = $manager->getConnection();
        $rawSql = "INSERT INTO espece_type
                    VALUES ('1', '10'),
                            ('1', '11'),
                            ('2', '10'),
                            ('2', '11'),
                            ('3', '10'),
                            ('3', '11'),
                            ('4', '6'),
                            ('5', '6'),
                            ('6', '6'),
                            ('6', '16'),
                            ('7', '4'),
                            ('8', '4'),
                            ('9', '4'),
                            ('10', '8'),
                            ('11', '8'),
                            ('12', '8'),
                            ('12', '16'),
                            ('13', '8'),
                            ('13', '11'),
                            ('14', '8'),
                            ('14', '11'),
                            ('15', '8'),
                            ('15', '11'),
                            ('16', '9'),
                            ('16', '16'),
                            ('17', '9'),
                            ('17', '16'),
                            ('18', '9'),
                            ('18', '16'),
                            ('19', '9'),
                            ('20', '9'),
                            ('21', '9'),
                            ('21', '16'),
                            ('22', '9'),
                            ('22', '16'),
                            ('23', '11'),
                            ('24', '11'),
                            ('25', '5'),
                            ('26', '5'),
                            ('27', '14'),
                            ('28', '14'),
                            ('29', '11'),
                            ('30', '11'),
                            ('31', '11'),
                            ('31', '14'),
                            ('32', '11'),
                            ('33', '11'),
                            ('34', '11'),
                            ('34', '14'),
                            ('35', '17'),
                            ('36', '17'),
                            ('37', '6'),
                            ('38', '6'),
                            ('39', '9'),
                            ('39', '17'),
                            ('40', '9'),
                            ('40', '17'),
                            ('41', '11'),
                            ('41', '16'),
                            ('42', '11'),
                            ('42', '16'),
                            ('43', '10'),
                            ('43', '11'),
                            ('44', '10'),
                            ('44', '11'),
                            ('45', '10'),
                            ('45', '11'),
                            ('46', '8'),
                            ('46', '10'),
                            ('47', '8'),
                            ('47', '10'),
                            ('48', '8'),
                            ('48', '11'),
                            ('49', '8'),
                            ('49', '11'),
                            ('50', '14'),
                            ('51', '14'),
                            ('52', '9'),
                            ('53', '9'),
                            ('54', '4'),
                            ('55', '4'),
                            ('56', '2'),
                            ('57', '2'),
                            ('58', '6'),
                            ('59', '6'),
                            ('60', '4'),
                            ('61', '4'),
                            ('62', '4'),
                            ('62', '2'),
                            ('63', '12'),
                            ('64', '12'),
                            ('65', '12'),
                            ('66', '2'),
                            ('67', '2'),
                            ('68', '2'),
                            ('69', '10'),
                            ('69', '11'),
                            ('70', '10'),
                            ('70', '11'),
                            ('71', '10'),
                            ('71', '11'),
                            ('72', '4'),
                            ('72', '11'),
                            ('73', '4'),
                            ('73', '11'),
                            ('74', '13'),
                            ('74', '14'),
                            ('75', '13'),
                            ('75', '14'),
                            ('76', '13'),
                            ('76', '14'),
                            ('77', '6'),
                            ('78', '6'),
                            ('79', '4'),
                            ('79', '12'),
                            ('80', '4'),
                            ('80', '12'),
                            ('81', '5'),
                            ('81', '1'),
                            ('82', '5'),
                            ('82', '1'),
                            ('83', '9'),
                            ('83', '16'),
                            ('84', '9'),
                            ('84', '16'),
                            ('85', '9'),
                            ('85', '16'),
                            ('86', '4'),
                            ('87', '4'),
                            ('87', '7'),
                            ('88', '11'),
                            ('89', '11'),
                            ('90', '4'),
                            ('91', '4'),
                            ('91', '7'),
                            ('92', '15'),
                            ('92', '11'),
                            ('93', '15'),
                            ('93', '11'),
                            ('94', '15'),
                            ('94', '11'),
                            ('95', '13'),
                            ('95', '14'),
                            ('96', '12'),
                            ('97', '12'),
                            ('98', '4'),
                            ('99', '4'),
                            ('100', '5'),
                            ('101', '5'),
                            ('102', '10'),
                            ('102', '12'),
                            ('103', '10'),
                            ('103', '12'),
                            ('104', '14'),
                            ('105', '14'),
                            ('106', '2'),
                            ('107', '2'),
                            ('108', '9'),
                            ('109', '11'),
                            ('110', '11'),
                            ('111', '14'),
                            ('111', '13'),
                            ('112', '14'),
                            ('112', '13'),
                            ('113', '9'),
                            ('114', '10'),
                            ('115', '9'),
                            ('116', '4'),
                            ('117', '4'),
                            ('118', '4'),
                            ('119', '4'),
                            ('120', '4'),
                            ('121', '4'),
                            ('121', '12'),
                            ('122', '12'),
                            ('122', '17'),
                            ('123', '8'),
                            ('123', '16'),
                            ('124', '7'),
                            ('124', '12'),
                            ('125', '5'),
                            ('126', '6'),
                            ('127', '8'),
                            ('128', '9'),
                            ('129', '4'),
                            ('130', '4'),
                            ('130', '16'),
                            ('131', '4'),
                            ('131', '7'),
                            ('132', '9'),
                            ('133', '9'),
                            ('134', '4'),
                            ('135', '5'),
                            ('136', '6'),
                            ('137', '9'),
                            ('138', '13'),
                            ('138', '4'),
                            ('139', '13'),
                            ('139', '4'),
                            ('140', '13'),
                            ('140', '4'),
                            ('141', '13'),
                            ('141', '4'),
                            ('142', '13'),
                            ('142', '16'),
                            ('143', '9'),
                            ('144', '7'),
                            ('144', '16'),
                            ('145', '5'),
                            ('145', '16'),
                            ('146', '6'),
                            ('146', '16'),
                            ('147', '3'),
                            ('148', '3'),
                            ('149', '3'),
                            ('149', '16'),
                            ('150', '12'),
                            ('151', '12');";
        $stmt = $conn->prepare($rawSql);
        $stmt->execute();
    }
}
